# Use the README file as a reference to customize settings.

Activity:
  fields:
    default: description, event_id, user_id, artist
    form: description, event_id, user_id, artist
  relationships: 
  application: Application
